### ISSUE TITLE
Current master server address

### ISSUE THREAD

**Issue by andy5995** [francov/netPanzerSB#14]
Ok if I submit a PR to update the master server address? It's [netpanzer.io](https://github.com/netpanzer/netpanzer/blob/437a575964ee66fbd078573eb4e9fd86cb0cae5a/src/NetPanzer/Interfaces/GameConfig.cpp#L424) now.

**Comment by francov** [comment]
Yes, it's ok, BUT consider this:

0. I think that changing only the master server address is not enough (there are JSON routes consumed that are based on a specific JSON format returned by the old server)
1. the project needs a complete rewrite/update, as It's about 6 years old
2. in order to rebuild and deploy the new apk, previous point 1) is required
3. consider that for online players notifications I opted out for a telegram bot that was hosted somewhere... and the related repo is https://github.com/francov/netPanzerTelegramBot

**Comment by andy5995** [comment]
Hi @francov 

Thanks for the info. I won't do anything for now, considering this as well https://github.com/netpanzer/serverbrowser-js/issues/1#issuecomment-1884335545
